version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo install commands started on `date`
      - echo install commands completed on `date`

  pre_build:
    commands:
      - echo `pwd`
      - echo yarn INSTALL started on `date`
      - yarn --version
      - yarn install
      - echo yarn INSTALL completed on `date`

  build:
    commands:
      - echo `pwd`
      - echo BUILD started on `date`
      - yarn run build
      - echo BUILD completed on `date`

artifacts:
  files:
    - '**/*'

env:
  exported-variables:
    - NODE_ENV
    - COGNITO_USER_POOL_ID
    - COGNITO_CLIENT_ID
    - COGNITO_REGION
    - COGNITO_AUTHORITY
    - ACCESS_KEY_ID
    - SECRET_ACCESS_KEY
    - MONGODB_URI

cache:
  paths:
    - 'node_modules/**/*'
