version: 0.2

phases:
    install:
        commands:
            - echo nodesource and yarn started on `date`
            - curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
            - sudo yum install -y nodejs
            - sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
            - sudo yum -y install yarn
            - echo nodesource and yarn completed on `date`
            
    pre_build:
        commands:
            - echo `pwd`
            - echo yarn INSTALL started on `date`
            - yarn install
            - echo yarn INSTALL completed on `date`
            
    build:
        commands:
            - echo `pwd`
            
            - echo yarn TEST started on `date`
            - cd packages/server
            - yarn test
            - cd ../..
            - echo yarn TEST completed on `date`
            
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
            
artifacts:
    files:
        - '**/*'
cache:
    paths:
        - 'node_modules/**/*'
        - 'packages/admin/node_modules/**/*'
        - 'packages/client/node_modules/**/*'
        - 'packages/server/node_modules/**/*'
