version: 0.2

phases:
    pre_build:
        commands:
            - yarn install
            - echo INSTALL completed on `date`
    build:
        commands:
            - echo `pwd`
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
artifacts:
    files:
        - '**/*'
