version: 0.2

phases:
    pre_build:
        commands:
            - yarn install
            - echo INSTALL completed on `date`
    build:
        commands:
            - echo `pwd`
            - echo TEST started on `date`
            - yarn --cwd packages/server/ test
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
artifacts:
    files:
        - '**/*'
cache:
    paths:
        - '/node_modules/*/**'
