version: 0.2

phases:
    pre_build:
        commands:
            - yarn install
            - echo INSTALL completed on `date`
    install:
        commands:
            - npm install --global yarn
    build:
        commands:
            - echo `pwd`
            
            #- echo TEST started on `date`
            #- cd packages/server
            #- yarn test
            #- cd ../..
            #- echo TEST completed on `date`
            
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
            
artifacts:
    files:
        - '**/*'
cache:
    paths:
        - '/node_modules/*/**'
