version: 0.2

phases:
    pre_build:
        commands:
            - yarn install
            - echo INSTALL completed on `date`
    install:
        commands:
            - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
            - sudo yum -y install yarn
    build:
        commands:
            - echo `pwd`
            
            - echo TEST started on `date`
            - cd packages/server
            - yarn test
            - cd ../..
            - echo TEST completed on `date`
            
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
            
artifacts:
    files:
        - '**/*'
cache:
    paths:
        - 'node_modules/**/*'
        - 'packages/admin/node_modules/**/*'
        - 'packages/client/node_modules/**/*'
        - 'packages/server/node_modules/**/*'
