version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    pre_build:
        commands:
            - yarn install
            - echo INSTALL completed on `date`
    build:
        commands:
            - echo `pwd`
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
artifacts:
    files:
        - '**/*'

cache:
    paths:
        - '/node_modules/*/**'
